/**
 * REDUX CONSTANTS
 */
export const LINK_FORM_SUBMIT_START = 'LINK_FORM_SUBMIT_START';
export const LINK_FORM_SUBMIT_END = 'LINK_FORM_SUBMIT_END';
export const LINK_FORM_SET_VALUE = 'LINK_FORM_SET_VALUE';

export const LINK_LIST_FETCH_REQUEST = 'LINK_LIST_FETCH_REQUEST';
export const LINK_LIST_FETCH_RESPONSE = 'LINK_LIST_FETCH_RESPONSE';
export const LINK_LIST_ADD_REQUEST = 'LINK_LIST_ADD_REQUEST';
export const LINK_LIST_ADD_RESPONSE = 'LINK_LIST_ADD_RESPONSE';
export const LINK_LIST_CLEAR = 'LINK_LIST_CLEAR';

export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const CLIPBOARD_COPY = 'CLIPBOARD_COPY';

/**
 * OTHER CONSTANTS
 */
export const SERVER = 'https://impraise-shorty.herokuapp.com/';
